version: '3'

services:

  # Back-end Spring boot application
  bibliotheque-app:
    build:
      context: ./bibliotheque-app
      args:
        maven_build_env: mvn -f pom.xml clean package
    environment:
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

    container_name: bibliotheque-app-local

    ports:
      - 8080:8080

  # Front-end Angular application
  bibliotheque-ui:

    build:
      context: ./bibliotheque-ui
      args:
        angular_build_env: node_modules/.bin/ng build
        env: local
    restart: always
    container_name: bibliotheque-ui-local
    ports:
      - 80:80
    links:
      - bibliotheque-app

volumes:
  bibliotheque-data:
