version: '3'

services:

  # Postgres
  bibliotheque-postgres:
    image: "postgres:13.2-alpine"
    container_name: bibliotheque-postgres

    volumes:
      - bibliotheque-data:/var/lib/postgresql/data

    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=bibliotheque
      - POSTGRES_USER=groupe2ws
      - POSTGRES_PASSWORD=12345

  # Back-end Spring boot application
  bibliotheque-app:
    build:
      context: ./bibliotheque-app
      args:
        maven_build_env: mvn -f pom.xml clean package

    container_name: bibliotheque-app-local

    ports:
      - 8080:8080
    links:
      - bibliotheque-postgres

  # Front-end Angular application
  bibliotheque-ui:

    build:
      context: ./bibliotheque-ui
      args:
        angular_build_env: node_modules/.bin/ng build
        env: local
    restart: always
    container_name: bibliotheque-ui-local
    ports:
      - 80:80
    links:
      - bibliotheque-app

volumes:
  bibliotheque-data:
