version: '3'

services:

  # Postgres
  bibliotheque-postgres:
    image: "postgres:13.2-alpine"
    container_name: bibliotheque-postgres

    volumes:
      - bibliotheque-data:/var/lib/postgresql/data

    ports:
      - 5433:5432

    environment:
      - POSTGRES_DB=bibliotheque
      - POSTGRES_USER=groupe2ws
      - POSTGRES_PASSWORD=${postgres_password}

  # Back-end Spring boot application
  bibliotheque-app:
    build:
      context: ./bibliotheque-app
      args:
        maven_build_env: ${maven_build_env}

    container_name: bibliotheque-app-${env}

    ports:
      - 8080:8080
    links:
      - bibliotheque-postgres

  # Front-end Angular application
  bibliotheque-ui:

    build:
      context: ./bibliotheque-ui
      args:
        angular_build_env: ${angular_build_env}
    restart: always
    container_name: bibliotheque-ui-${env}
    volumes:
      - letsencrypt:/etc/letsencrypt
    ports:
      - 19000:80
      - 443:443
    links:
      - bibliotheque-app

volumes:
  bibliotheque-data:
