version: '3'

services:

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: always
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_home:/home
    networks:
      - jenkinsnet

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - /opt/nexus/:/var/lib/nexus
      - nexus_data:/nexus-data
    networks:
      - jenkinsnet
    depends_on:
      - jenkins

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
    links:
      - sonardb
    networks:
      - jenkinsnet
    depends_on:
      - jenkins

  sonardb:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRESQL_DB=sonar
    ports:
      - "5432:5432"
    volumes:
      - /opt/postgres:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - jenkinsnet
    depends_on:
      - jenkins


networks:
  jenkinsnet:
    driver: bridge

volumes:
  jenkins_data:
  jenkins_home:
  nexus_data:
  sonarqube_data:
  postgresql_data:
