---

- include_vars: vault.yml
  tags:
    - filebeat

# ADD GPG KEY ELASTICSEARCH
- name: Get and add elasticSearch gpg-key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  become: yes
  tags:
    - filebeat

# ADD REPO ELASTICSEARCH
- name: Add repository elasticSearch
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
    update_cache: true
  become: yes
  tags:
    - filebeat

# INSTALL FILEBEAT
- name: Install filebeat
  apt:
    name: filebeat
    state: present
  become: yes
  tags:
    - filebeat

# MODIFY FILEBEAT CONFIG
- name: Modify filebeat config file
  template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    force: yes
  become: yes
  tags:
    - filebeat

# START FILEBEAT
- name: start filebeat
  service:
    name: filebeat
    state: started
    enabled: yes
  become: yes
  tags:
    - filebeat

# ENABLE FILEBEAT SYSTEM MODULE
- name: Enable filebeat system module
  command: filebeat modules enable system
  become: yes
  tags:
    - filebeat

# SETUP FILEBEAT
- name: setup filebeat
  command: filebeat setup --index-management -E output.logstash.enabled=false -E 'output.elasticsearch.hosts={{ elastic_hosts }}:9200'
  become: yes
  tags:
    - filebeat

# RESTART FILEBEAT
- name: restart filebeat
  service:
    name: filebeat
    state: restarted
  become: yes
  tags:
    - filebeat