spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://51.255.211.147:5432/bibliotheque
    username: groupe2ws
    password: 12345
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect