version: "3.8"

services:

  filebeat:
    image: dhaeseq/projet-fil-rouge-groupe2:filebeat-{{ env }}
    # Need to override user so we can access the log files, and docker.sock
    user: root
    volumes:
      - filebeat:/usr/share/filebeat/data
      - /var/run/docker.sock:/var/run/docker.sock
      # This is needed for filebeat to load container log path as specified in filebeat.yml
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      # This is needed for filebeat to load logs for system and auth modules
      - /var/log/:/var/log/:ro
    # disable strict permission checks https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html
    command: filebeat -e -strict.perms=false
    deploy:
      mode: global

volumes:
  filebeat:
