---

- hosts: local
  roles:
    - { role: docker }
    - { role: dokuwiki }
    - { role: bibliothequeapplication }
    - { role: elk }

- hosts: devfilrouge
  roles:
    - { role: common }
    - { role: docker }
    - { role: dokuwiki }
    - { role: bibliothequeapplication }

- hosts: prodfilrouge
  roles:
    - { role: common }
    - { role: docker }
    - { role: bibliothequeapplication }

- hosts: elk1
  roles:
    - { role: common }
    - { role: docker }
    - { role: elk }