---

- hosts: local
  roles:
    - { role: docker }
    - { role: dokuwiki }
    - { role: bibliothequeapplication }
    - { role: elk }
    - { role: filebeat }
    - { role: jenkins }

- hosts: filrougeservers
  roles:
    - { role: common }
    - { role: usersfilrouge }
    - { role: docker }
    - { role: dokuwiki, when: inventory_hostname == "devfilrouge" }
    - { role: bibliothequeapplication }
    - { role: filebeat }
    - { role: portainer }
    - { role: nodeexporter }

- hosts: elk1
  roles:
    - { role: common }
    - { role: usersfilrouge }
    - { role: docker }
    - { role: elk }
    - { role: portainer }
    - { role: nodeexporter }

- hosts: jenkins
  roles:
    - { role: common }
    - { role: usersfilrouge }
    - { role: docker }
    - { role: jenkins }
    - { role: portainer }
    - { role: bibliothequeapplication }
    - { role: prometheus }
