---

#- hosts: local
#  roles:
#    - { role: docker }
#    - { role: dokuwiki }
#    - { role: bibliothequeapplication }
#    - { role: elk }
#    - { role: filebeat }
#
#- hosts: filrougeservers
#  roles:
#    - { role: common }
#    - { role: usersfilrouge }
#    - { role: docker }
#    - { role: dokuwiki, when: inventory_hostname == "devfilrouge" }
#    - { role: bibliothequeapplication }
#    - { role: filebeat }
#
#- hosts: elk1
#  roles:
#    - { role: common }
#    - { role: usersfilrouge }
#    - { role: docker }
#    - { role: elk }

- hosts: jenkins
  roles:
#    - { role: common }
#    - { role: usersfilrouge }
#    - { role: docker }
#    - { role: jenkins }
    - { role: git }
    - { role: awx }
