version: '3'

services:

  # Postgres
  bibliotheque-postgres:
    image: "postgres:13.2-alpine"
    container_name: bibliotheque-postgres

    volumes:
      - bibliotheque-data:/var/lib/postgresql/data

    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=bibliotheque
      - POSTGRES_USER=groupe2ws
      - POSTGRES_PASSWORD={{ pg_password }}

  # Back-end Spring boot application
  bibliotheque-app:
    image: dhaeseq/projet-fil-rouge-groupe2:bibliotheque-app-{{ env }}
    environment:
      - SPRING_PROFILES_ACTIVE={{ env }}
      - SPRING_DATASOURCE_PASSWORD={{ pg_password }}
    container_name: bibliotheque-app
    ports:
      - 8080:8443
    links:
      - bibliotheque-postgres

  # Front-end Angular application
  bibliotheque-ui:
    image: dhaeseq/projet-fil-rouge-groupe2:bibliotheque-ui-{{ env }}
    container_name: bibliotheque-ui
    restart: always
    volumes:
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    links:
      - bibliotheque-app

volumes:
  bibliotheque-data:
  letsencrypt:
