---

# BUILD PREPROD FILEBEAT IMAGE AND PUSH DOCKERHUB
- name: Build preprod filebeat image and send it to DockerHub
  docker_image:
    build:
      path: "{{ role_path }}/files"
      args:
        env: preprod
    source: build
    name: dhaeseq/projet-fil-rouge-groupe2:filebeat-preprod
    tag: latest
    push: yes
  when: inventory_hostname == "localhost"
  tags:
    - buildAndPushFilebeatPreprodImage
    - freshInstallFilebeat

# REMOVE PREPROD FILEBEAT LOCAL IMAGE
- name: Remove preprod filebeat local image
  docker_image:
    state: absent
    name: dhaeseq/projet-fil-rouge-groupe2
    tag: filebeat-preprod
  when: inventory_hostname == "localhost"
  tags:
    - buildAndPushFilebeatPreprodImage
    - removeLocalFilebeatPreprodImage
    - freshInstallFilebeat

# BUILD PROD FILEBEAT IMAGE AND PUSH DOCKERHUB
- name: Build prod filebeat image and send it to DockerHub
  docker_image:
    build:
      path: "{{ role_path }}/files"
      args:
        env: prod
    source: build
    name: dhaeseq/projet-fil-rouge-groupe2:filebeat-prod
    tag: latest
    push: yes
  when: inventory_hostname == "localhost"
  tags:
    - buildAndPushFilebeatProdImage
    - freshInstallFilebeat

# REMOVE PROD FILEBEAT LOCAL IMAGE
- name: Remove prod filebeat local image
  docker_image:
    state: absent
    name: dhaeseq/projet-fil-rouge-groupe2
    tag: filebeat-prod
  when: inventory_hostname == "localhost"
  tags:
    - buildAndPushFilebeatProdImage
    - removeLocalFilebeatProdImage
    - freshInstallFilebeat

# RUN FILEBEAT IMAGE
- name: Run filebeat image
  docker_container:
    detach: yes
    image: dhaeseq/projet-fil-rouge-groupe2:filebeat-{{ env }}
    pull: yes
    recreate: yes
    volumes:
      - filebeat:/usr/share/filebeat/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      - /var/log/:/var/log/:ro
    name: filebeat
    user: root
    command: "filebeat -e -strict.perms=false"
    restart_policy: always
  when: inventory_hostname in groups.filrougeservers
  tags:
    - runFilebeatImage
    - freshInstallFilebeat

# PRUNE IMAGES
- name: Prune docker images
  docker_prune:
    images: yes
  tags:
    - pruneImages
    - freshInstallFilebeat
