---

# CREATE USERS
- name: Create users for filRouge project
  user:
    name: "{{ item.username }}"
    create_home: yes
    password: "{{ 'password' | password_hash('sha512') }}"
    update_password: on_create
    shell: /bin/bash
    groups: "{{ item.groups }}"
    state: present
  with_items: "{{ users }}"
  become: yes
  tags:
    - createUsersFilRouge
    - freshMakeUsersFilRouge

- name: Make passwords expire for all users
  command: chage -d 0 {{ item.username }}
  with_items: "{{ users }}"
  become: yes
  tags:
    - expireAllPasswordsFilRouge
    - freshMakeUsersFilRouge

# SSH
- name: Create key files
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ lookup('file', 'files/' + item.username + '.key.pub') }}"
  with_items: "{{ users }}"
  become: yes
  tags:
    - registerSshKeysUsersFilRouge
    - freshMakeUsersFilRouge
