---

ansible_host: "{{ vault_ansible_host }}"
ansible_ssh_user: "{{ vault_ansible_ssh_user }}"
ansible_ssh_password: "{{ vault_ansible_ssh_password }}"
java_password: "{{ vault_java_password }}"
ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
pg_password: "{{ vault_pg_password }}"
pg_settings:
  db_users:
    - name : "Groupe2"
      password: "{{ vault_password_postgres_user }}"
  db_name:
    - name : "Bibliotheque"
      owner : "Groupe2"
