---

- hosts: filrougeservers
  roles:
    - { role: handlers }
    - { role: common }
    - { role: usersfilrouge }
    - { role: dokuwiki, when: inventory_hostname == "devfilrouge" }
    - { role: filrougeangular }
    - { role: filrougejava }
    - { role: postgresql }
    - { role: filebeat }
    - { role: docker }


- hosts: elkservers
  roles:
    - { role: common }
    - { role: usersfilrouge }
    - { role: docker }
    - { role: elk }
