---

- hosts: filrougeservers
  roles:
    - { role: common }
    - { role: usersfilrouge }
    - { role: dokuwiki, when: inventory_hostname == "devfilrouge" }
    - { role: filrougeangular }
    - { role: filrougejava }

- hosts: elkservers
  roles:
    - { role: common }
    - { role: usersfilrouge }
# todo referencement tags dans un fichier pour suivie facile
# todo changer cron.md pour readme et attention branche sauvegarde + propre sur tout le projet + Readme partout


