---

ansible_host: "{{ vault_ansible_host }}"
ansible_ssh_user: "{{ vault_ansible_ssh_user }}"
ansible_ssh_password: "{{ vault_ansible_ssh_password }}"
ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
java_password: "{{ vault_java_password }}"
