---

- include_vars: vault.yml
  tags:
    - getDokuWiki
    - copyConfigDokuWiki
    - renameArchiveDokuWiki
    - freshInstallDokuWiki


# GET DOKUWIKI
- name: Check if dokuwiki archive exists
  stat:
    path: /var/www/html/dokuwiki-stable.tgz
  register: dokuwikiArchive
  tags:
    - getDokuWiki
    - freshInstallDokuWiki

- name: Check if extracted dokuwiki archive exists
  stat:
    path: /var/www/html/dokuwiki-{{ dokuwiki_version }}
  register: extractedDokuWikiArchive
  tags:
    - getDokuWiki
    - freshInstallDokuWiki

- name: Check if dokuwiki exists
  stat:
    path: /var/www/html/dokuwiki
  register: finalDokuwiki
  tags:
    - getDokuWiki
    - freshInstallDokuWiki

- name: Get dokuwiki
  get_url:
    url: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
    dest: /var/www/html
  become: yes
  when: (dokuwikiArchive.stat.exists == false) or (extractedDokuWikiArchive.stat.exists) or (finalDokuwiki.stat.exists)
  tags:
    - getDokuWiki
    - freshInstallDokuWiki

# UNARCHIVE DOKUWIKI
- name: Check if dokuwiki archive exists
  stat:
    path: /var/www/html/dokuwiki-stable.tgz
  register: dokuwikiArchive
  tags:
    - unarchiveDokuWiki
    - removeArchiveDokuWiki
    - freshInstallDokuWiki

- name: Unarchive dokuwiki
  unarchive:
    src: /var/www/html/dokuwiki-stable.tgz
    dest: /var/www/html
    owner: www-data
    group: www-data
    mode: 0775
    remote_src: yes
  become: yes
  when: dokuwikiArchive.stat.exists
  tags:
    - unarchiveDokuWiki
    - freshInstallDokuWiki

- name: Remove archive
  file:
    state: absent
    path: /var/www/html/dokuwiki-stable.tgz
  become: yes
  when: dokuwikiArchive.stat.exists
  tags:
    - unarchiveDokuWiki
    - removeArchiveDokuWiki
    - freshInstallDokuWiki

- name: Check if extracted dokuwiki archive exists
  stat:
    path: /var/www/html/dokuwiki-{{ dokuwiki_version }}
  register: extractedDokuWikiArchive
  tags:
    - unarchiveDokuWiki
    - renameArchiveDokuWiki
    - freshInstallDokuWiki

- name: Rename folder
  command: mv /var/www/html/dokuwiki-{{ dokuwiki_version }} /var/www/html/dokuwiki
  become: yes
  when: extractedDokuWikiArchive.stat.exists
  tags:
    - unarchiveDokuWiki
    - renameArchiveDokuWiki
    - freshInstallDokuWiki

# APACHE CONFIG
- name: Write the apache config file
  template:
    src: dokuwiki.conf
    dest: /etc/apache2/sites-available/dokuwiki.conf
  become: yes
  tags:
    - copyConfigDokuWiki
    - freshInstallDokuWiki

- name: Add port to apache conf
  lineinfile:
    path: /etc/apache2/ports.conf
    line: 'Listen 8081'
  become: yes
  tags:
    - addPortDokuWiki
    - freshInstallDokuWiki

# ENABLE DOKUWIKI SITES
- name: Enable sites
  command: a2ensite dokuwiki.conf
  become: yes
  notify:
    - restart apache2
  tags:
    - enableSiteDokuWiki
    - freshInstallDokuWiki

# BUILD DOKUWIKI
- name: Copy dokuwiki build files
  unarchive:
    src: dokuwiki.tar.gz
    dest: /var/www/html/dokuwiki
    owner: www-data
    group: www-data
    mode: 0775
  become: yes
  tags:
    - copyDataDokuWiki
    - freshInstallDokuWiki
